# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config)

1.21.4
<function show at 0x000001DDA7935940>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
array1 = np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
array1.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x000001DDA78A01F0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
zarray = np.zeros(10)
zarray[4] = 1
print(zarray)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
array1 = np.arange(10, 49)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
reverse= array1[::-1]
reverse

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [11]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [13]:
i_m = np.eye(3)
i_m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [17]:
rand3array = np.random.random((3,3,3))
rand3array

array([[[0.65433942, 0.27398285, 0.77597063],
        [0.91974398, 0.64895756, 0.50994572],
        [0.34197806, 0.96067971, 0.79380675]],

       [[0.58475282, 0.68740876, 0.48350804],
        [0.57172411, 0.76480727, 0.34393209],
        [0.53282948, 0.64124873, 0.09539823]],

       [[0.43077189, 0.42720568, 0.67044304],
        [0.38574772, 0.98284097, 0.60098023],
        [0.44616943, 0.55097629, 0.51351578]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [19]:
tenarray = np.random.random((10,10))
Min, Max = tenarray.min(), tenarray.max()
print(Min, Max)

0.032258127262206227 0.9962976855166045


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [20]:
rvector = np.random.random(30)
avg = rvector.mean()
avg

0.5292965395393744

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [21]:
M = np.ones((5,5))
M[1:-1, 1:-1] = 0
M

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [22]:
M = np.ones((5,5))
M = np.pad(M, pad_width=1, mode='constant', constant_values = 0)
M

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [23]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [24]:
M = np.diag(1+np.arange(4),k=-1)
print(M)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [25]:
M = np.zeros((8,8),dtype=int)
M[1::2,::2] = 1
M[::2,1::2] = 1
M

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [26]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [27]:
M = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(M)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [28]:
M = np.random.random((5,5))
M = (M - np.mean (M)) / (np.std (M))
M

array([[-1.41337644,  0.44773698,  0.9334881 , -1.06324554, -0.40210844],
       [-1.1555781 , -0.33556882,  1.334951  ,  1.32073789, -0.83709367],
       [ 1.63593718,  0.69497408, -1.07655814, -0.8167849 , -1.27546317],
       [ 1.05047259,  0.14749735, -1.34563517,  1.05846328,  0.89567676],
       [ 0.10133538,  1.31423657, -1.31216253, -0.07002622,  0.16809395]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [30]:
colour = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\amin0\AppData\Local\Temp/ipykernel_11644/2911720781.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [31]:
M = np.dot(np.ones((5,3)), np.ones((3,2)))
M


array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [32]:
M = np.arange(11)
M[(3 < M) & (M <= 8)] *= -1
print(M)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [33]:
print(sum(range(5),-1))

from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

```

In [40]:
Z = np.arange(5)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z #This is not valid

'2 << Z >> 2\nZ <- Z\n1j*Z\nZ/1/1\nZ<Z>Z'

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [41]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\amin0\AppData\Local\Temp/ipykernel_11644/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\amin0\AppData\Local\Temp/ipykernel_11644/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [42]:
M = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(M)), M))

[ 3.  9. -9.  5. -6.  4.  5.  8. -4.  8.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [44]:
X = np.random.randint(0,10,10)
Y = np.random.randint(0,10,10)
Z = np.intersect1d(X,Y)
print(Z)

[1 2 4 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [45]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [46]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\amin0\AppData\Local\Temp/ipykernel_11644/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [48]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-03-06
2022-03-07
2022-03-08


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [49]:
D = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(D)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [50]:
X = np.ones(3)*1
Y = np.ones(3)*2
Z = np.ones(3)*3
np.add(X,Y,out=Y)
np.divide(X,2,out=X)
np.negative(X,out=X)
np.multiply(X,Y,out=X)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [51]:
D = np.random.uniform(0,10,10)

print (D - D%1)
print (np.floor(D))
print (np.ceil(D)-1)
print (D.astype(int))
print (np.trunc(D))

[9. 1. 3. 1. 7. 3. 7. 4. 5. 4.]
[9. 1. 3. 1. 7. 3. 7. 4. 5. 4.]
[9. 1. 3. 1. 7. 3. 7. 4. 5. 4.]
[9 1 3 1 7 3 7 4 5 4]
[9. 1. 3. 1. 7. 3. 7. 4. 5. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [52]:
D = np.zeros((5,5))
D += np.arange(5)
print(D)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [53]:
def gen():
    for x in range(10):
        yield x
D = np.fromiter(gen(),dtype=float,count=-1)
print(D)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [54]:
D = np.linspace(0,1,11,endpoint=False)[1:]
print(D)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [55]:
A = np.random.random(10)
A.sort()
print(A)

[0.19845675 0.28554815 0.47825127 0.77517758 0.80395588 0.82474824
 0.84891129 0.92056246 0.94749598 0.97824319]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [56]:
A = np.arange(10)
np.add.reduce(A)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [57]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [58]:
M = np.zeros(10)
M.flags.writeable = False
M[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [59]:
A = np.random.random((10,2))
X,Y = A[:,0], A[:,1]
U = np.sqrt(X**2+Y**2)
V = np.arctan2(Y,X)
print(U)
print(V)

[0.98813986 0.9268842  1.00015386 0.74440199 0.99462781 1.0682059
 0.72452468 1.19969372 0.92705669 0.37874924]
[0.51578852 0.08276981 1.10348644 1.32245416 1.17133651 0.69203879
 0.84736937 0.82751733 0.48301613 0.03801332]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [60]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.40876128 0.46824651 0.2357908  0.88696021 0.38828594 0.11857998
 0.78894254 0.         0.23687325 0.02556465]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [61]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [62]:
X = np.arange(8)
Y = X + 0.5
Z = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(Z))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [63]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [66]:
np.set_printoptions(threshold=np.nan)
M = np.zeros((16,16))
print(M)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [67]:
A = np.arange(100)
B = np.random.uniform(0,100)
index = (np.abs(A-B)).argmin()
print(A[index])

52


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [68]:
A = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(A)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\amin0\AppData\Local\Temp/ipykernel_11644/2208650056.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  A = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [69]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)


import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.18240467 0.3637094  0.18382357 0.79708439 0.89554928
  0.09480888 0.73125688 0.05599537 0.47682629]
 [0.18240467 0.         0.31515152 0.31774354 0.7177232  0.74947655
  0.22427959 0.55012877 0.13306307 0.41852637]
 [0.3637094  0.31515152 0.         0.31598421 0.4337477  0.59448612
  0.30192147 0.67088585 0.32031943 0.11317941]
 [0.18382357 0.31774354 0.31598421 0.         0.72977343 0.90546012
  0.09712105 0.85291823 0.19825847 0.41587843]
 [0.79708439 0.7177232  0.4337477  0.72977343 0.         0.37876973
  0.73350315 0.81203019 0.75155654 0.32132403]
 [0.89554928 0.74947655 0.59448612 0.90546012 0.37876973 0.
  0.86819766 0.5649164  0.84035789 0.52091894]
 [0.09480888 0.22427959 0.30192147 0.09712105 0.73350315 0.86819766
  0.         0.7678575  0.10113874 0.41242007]
 [0.73125688 0.55012877 0.67088585 0.85291823 0.81203019 0.5649164
  0.7678575  0.         0.68313147 0.69531357]
 [0.05599537 0.13306307 0.32031943 0.19825847 0.75155654 0.84035789
  0.10113874 0.683131

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [70]:
A = np.arange(10, dtype=np.float32)
A = A.astype(np.int32, copy=False)
print(A)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [71]:
from io import StringIO


S = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
T = np.genfromtxt(S, delimiter=",", dtype=np.int)
print(T)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\amin0\AppData\Local\Temp/ipykernel_11644/1600919783.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  T = np.genfromtxt(S, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [72]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [73]:
A, B = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
C = np.sqrt(A*A+B*B)
sigma, mu = 1.0, 0.0
D = np.exp(-( (C-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(D)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [74]:
n = 10
s = 3
M = np.zeros((n,n))
np.put(M, np.random.choice(range(n*n), s, replace=False),1)
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [75]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.28162708 -0.52889049 -0.45135053  0.4114698   0.37541286  0.3305259
   0.02853448 -0.12492106 -0.13402425 -0.18838377]
 [ 0.21963111 -0.06008268 -0.20661816  0.19214918 -0.24000488  0.26632736
  -0.42038874 -0.07484931  0.37659293 -0.05275682]
 [ 0.00645104 -0.39950245  0.07803972  0.36530529 -0.42289279 -0.15438955
  -0.15237029 -0.16049668  0.35802008  0.48183563]
 [-0.11807292  0.16142866 -0.11513789  0.00999444 -0.37296943 -0.12436984
   0.24138923 -0.3645648   0.39327732  0.28902523]
 [-0.13374769  0.218762    0.44455765  0.26567804 -0.26155959 -0.41382367
  -0.01464068 -0.12442403  0.14922966 -0.13003169]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [76]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 8 5]
 [8 0 1]
 [6 5 7]]
[[8 0 1]
 [6 5 7]
 [4 8 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [77]:
N = np.random.randint(0,3,(3,10))
print((~N.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [78]:
N = np.random.uniform(0,1,10)
a = 0.5
m = N.flat[np.abs(N - a).argmin()]
print(m)

0.4133509597669923


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [79]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
ite = np.nditer([A,B,None])
for x,y,z in ite: z[...] = x + y
print(ite.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [80]:
class Named(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = Named(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [81]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[4. 4. 3. 3. 2. 3. 2. 2. 3. 4.]
[7. 7. 5. 5. 3. 5. 3. 3. 5. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [82]:
M = [1,2,3,4,5,6]
N = [1,3,9,3,4,1]
O = np.bincount(N,M)
print(O)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [83]:
a,b = 16,16
I = np.random.randint(0,2,(b,a,3)).astype(np.ubyte)

F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [84]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[52 63 47 48]
 [59 67 52 54]
 [42 41 58 46]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [85]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.3823482  0.49339187 0.30601546 0.5512459  0.51128301 0.67324812
 0.52317362 0.49798727 0.48331175 0.60600943]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [86]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.sum(A * B.T, axis=1)

array([0.83889079, 1.28613453, 1.48429112, 1.24325093, 0.63091308])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [87]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [88]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [89]:
N = np.arange(25).reshape(5,5)
N[[0,1]] = N[[1,0]]
print(N)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [90]:
faces = np.random.randint(0,100,(10,3))
M = np.roll(faces.repeat(2,axis=1),-1,axis=1)
M = M.reshape(len(M)*3,2)
M = np.sort(M,axis=1)
G = M.view( dtype=[('p0',M.dtype),('p1',M.dtype)] )
G = np.unique(G)
print(G)

[( 3, 15) ( 3, 64) ( 9, 13) ( 9, 58) (12, 29) (12, 37) (13, 58) (13, 64)
 (13, 68) (15, 64) (22, 91) (22, 95) (29, 37) (29, 77) (29, 97) (31, 68)
 (31, 84) (39, 45) (39, 96) (45, 96) (46, 47) (46, 48) (46, 72) (46, 75)
 (47, 75) (48, 72) (64, 68) (68, 84) (77, 97) (91, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [91]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [92]:
def mov_avg(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(mov_avg(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [94]:
from numpy.lib import stride_tricks

def roll(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = roll(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [95]:
N = np.random.randint(0,2,100)
np.logical_not(N, out=N)

N = np.random.uniform(-1.0,1.0,100)
np.negative(N, out=N)

array([-0.13345921, -0.70919842,  0.78560576,  0.64685577, -0.37405401,
        0.8001996 ,  0.19075151, -0.65753729,  0.7921691 ,  0.00628838,
       -0.79907436,  0.94955147,  0.13692761, -0.37987951,  0.19392136,
        0.4807049 ,  0.97916871,  0.75428864,  0.94815576, -0.7327159 ,
       -0.41459862, -0.54008259,  0.69611389, -0.14493562, -0.02645604,
       -0.98520015,  0.79225299, -0.25329205,  0.99126967, -0.05956898,
        0.3695858 , -0.81788574, -0.27244804, -0.57561838,  0.80929701,
       -0.83813609, -0.58520067,  0.81460304,  0.43264941, -0.23782036,
        0.27009534,  0.97180969, -0.38817919, -0.72298824, -0.59311072,
        0.07980869, -0.29398825, -0.86640872,  0.96859868,  0.89735003,
       -0.87549182,  0.22835212, -0.76215567,  0.0559988 , -0.7870634 ,
       -0.7618116 , -0.11301005, -0.72976138, -0.9233469 ,  0.73078531,
       -0.94812951, -0.47711246,  0.04217178,  0.39595848, -0.89281813,
        0.5784345 ,  0.43874456, -0.78218056,  0.57857334, -0.92

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [96]:
def dist(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(dist(P0, P1, p))

[1.38755431 7.02216461 8.38805113 2.13453607 1.39042129 7.94953765
 6.36473953 7.51851656 6.23539017 4.39274668]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [98]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([dist(P0,P1,p_i) for p_i in p]))

[[ 1.37561984  7.96856754  3.04011579  2.63544614  6.60469864  6.22788776
  15.77536772 13.78146924  9.41891282  1.23181324]
 [ 3.85465009  4.53013146  7.20543638  6.32702515 12.61646853 13.40495244
   0.83945222  0.65683201  6.1890343   3.97771204]
 [ 5.52229031  5.83974471  6.24059671  5.22633223 11.27273219 12.14719438
   0.95721032  0.39033506  6.40190156  5.64492742]
 [ 9.21398026  3.16369799  9.07016955  9.16565997  0.7364351   0.84192516
  18.26310209 16.93292299 10.37572812  6.2549597 ]
 [ 1.07830618  1.84185142  8.24944098  7.64925074 14.46798075 15.06337834
   1.37088012  0.38634123  5.09847848  1.07059292]
 [15.56686355 13.0264204   0.34724853  2.10792148  2.6466997   3.97006338
   2.67097139  2.20093334  6.66757046 15.50539448]
 [13.7056736   1.65264536 10.2421502  10.83561965  3.37732921  3.12450703
  16.73438409 15.83860144  7.93443559 11.07913175]
 [14.17187453 12.99612296  1.63890894  0.11726065  4.57927034  5.93544545
   1.04703304  0.48048721  8.03316447 14.3864646 ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [99]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 6 5 5 9 0 8 4 7 7]
 [1 2 4 2 3 6 2 3 4 5]
 [8 1 8 8 2 5 9 6 3 9]
 [3 5 3 7 3 9 0 8 3 2]
 [9 3 4 0 9 7 0 2 7 6]
 [4 7 5 5 0 2 0 1 3 9]
 [3 2 3 0 2 8 2 3 4 3]
 [7 0 4 6 2 8 0 5 7 8]
 [7 8 9 2 5 2 5 1 8 8]
 [9 8 9 6 5 8 0 1 2 4]]
[[0 0 0 0 0]
 [0 7 6 5 5]
 [0 1 2 4 2]
 [0 8 1 8 8]
 [0 3 5 3 7]]


C:\Users\amin0\AppData\Local\Temp/ipykernel_11644/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [100]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [101]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [102]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [103]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 1]
   [3 2 3]
   [3 2 0]]

  [[4 1 4]
   [2 3 4]
   [2 0 4]]

  [[1 4 4]
   [3 4 2]
   [0 4 0]]

  [[4 4 2]
   [4 2 1]
   [4 0 1]]

  [[4 2 3]
   [2 1 0]
   [0 1 2]]

  [[2 3 2]
   [1 0 3]
   [1 2 0]]

  [[3 2 2]
   [0 3 0]
   [2 0 0]]

  [[2 2 2]
   [3 0 1]
   [0 0 0]]]


 [[[3 2 3]
   [3 2 0]
   [0 1 2]]

  [[2 3 4]
   [2 0 4]
   [1 2 2]]

  [[3 4 2]
   [0 4 0]
   [2 2 1]]

  [[4 2 1]
   [4 0 1]
   [2 1 4]]

  [[2 1 0]
   [0 1 2]
   [1 4 2]]

  [[1 0 3]
   [1 2 0]
   [4 2 0]]

  [[0 3 0]
   [2 0 0]
   [2 0 0]]

  [[3 0 1]
   [0 0 0]
   [0 0 1]]]


 [[[3 2 0]
   [0 1 2]
   [3 1 2]]

  [[2 0 4]
   [1 2 2]
   [1 2 1]]

  [[0 4 0]
   [2 2 1]
   [2 1 4]]

  [[4 0 1]
   [2 1 4]
   [1 4 4]]

  [[0 1 2]
   [1 4 2]
   [4 4 2]]

  [[1 2 0]
   [4 2 0]
   [4 2 1]]

  [[2 0 0]
   [2 0 0]
   [2 1 4]]

  [[0 0 0]
   [0 0 1]
   [1 4 4]]]


 [[[0 1 2]
   [3 1 2]
   [3 3 2]]

  [[1 2 2]
   [1 2 1]
   [3 2 1]]

  [[2 2 1]
   [2 1 4]
   [2 1 3]]

  [[2 1 4]
   [1 4 4]
   [1 3 2]]

  [[1 4 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [105]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[3,1] = 42
print(S)

[[ 2 11 14  5 10]
 [11  0  4 42  6]
 [14  4  2  8  3]
 [ 5 42  8  3  5]
 [10  6  3  5  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [106]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [107]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [108]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

   
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [109]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9997 9999 9996 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [110]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [111]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [112]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [113]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [114]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[0 1 4]
 [4 3 3]
 [3 1 4]
 [3 4 1]
 [2 1 0]
 [1 4 2]
 [3 2 2]
 [1 4 0]
 [4 4 4]
 [1 4 0]]
[[0 1 4]
 [4 3 3]
 [3 1 4]
 [3 4 1]
 [2 1 0]
 [1 4 2]
 [3 2 2]
 [1 4 0]
 [1 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [115]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [116]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [117]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.1661251 , 0.16724821, 0.29410872, 0.38816901, 0.19676513,
        0.04117379, 0.04502142, 0.1847973 , 0.34991302, 0.36906503],
       [0.11023098, 0.11097621, 0.19515349, 0.25756645, 0.13056193,
        0.02732054, 0.0298736 , 0.12262077, 0.23218199, 0.24489015],
       [0.2574226 , 0.25916294, 0.45574228, 0.60149536, 0.30490149,
        0.06380171, 0.06976388, 0.28635649, 0.54221499, 0.57189238],
       [0.01231287, 0.01239612, 0.02179877, 0.02877034, 0.01458385,
        0.00305172, 0.0033369 , 0.01369682, 0.02593488, 0.02735439],
       [0.22627527, 0.22780503, 0.40059889, 0.5287163 , 0.26800937,
        0.0560819 , 0.06132266, 0.25170825, 0.47660867, 0.50269519],
       [0.20641796, 0.20781348, 0.36544341, 0.48231758, 0.24448959,
        0.0511603 , 0.05594115, 0.22961901, 0.43478278, 0.45858001],
       [0.13937032, 0.14031254, 0.24674191, 0.3256536 , 0.1650757 ,
        0.03454267, 0.03777063, 0.15503532, 0.29355881, 0.30962635],
       [0.16241861, 0.16351666, 0.2875467

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [118]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [119]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [120]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.07721287  0.3600705 ]
